import { sqliteTable, text, integer, index } from "drizzle-orm/sqlite-core";
import { relations } from "drizzle-orm";
import { user } from "./auth-schema";

// Auth tables (user, session, account, verification) are generated by
// better-auth: `npx @better-auth/cli generate`. Domain tables live here.
export * from "./auth-schema";

const id = () =>
  text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID());

const createdAt = () =>
  integer("created_at", { mode: "timestamp_ms" })
    .notNull()
    .$defaultFn(() => new Date());

export const PROJECT_STATES = [
  "PROPOSAL",
  "SCOPING",
  "ACTIVE",
  "BLOCKED",
  "PAUSED",
  "DONE",
  "KILLED",
] as const;
export type ProjectState = (typeof PROJECT_STATES)[number];

export const projects = sqliteTable(
  "projects",
  {
    id: id(),
    title: text("title").notNull(),
    description: text("description").notNull().default(""),
    ownerId: text("owner_id")
      .notNull()
      .references(() => user.id),
    advisorId: text("advisor_id")
      .notNull()
      .references(() => user.id),
    state: text("state", { enum: PROJECT_STATES }).notNull().default("PROPOSAL"),
    // required at app level whenever state === PAUSED
    pauseReason: text("pause_reason"),
    reviveDate: integer("revive_date", { mode: "timestamp_ms" }),
    // Heilmeier Catechism
    objective: text("objective").notNull().default(""),
    howItsDoneToday: text("how_its_done_today").notNull().default(""),
    whatsNew: text("whats_new").notNull().default(""),
    whoCares: text("who_cares").notNull().default(""),
    risks: text("risks").notNull().default(""),
    killCriteria: text("kill_criteria").notNull().default(""),
    successCriteria: text("success_criteria").notNull().default(""),
    createdAt: createdAt(),
  },
  (t) => [
    index("projects_state_idx").on(t.state),
    index("projects_owner_idx").on(t.ownerId),
  ]
);

export const stateTransitions = sqliteTable(
  "state_transitions",
  {
    id: id(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id),
    fromState: text("from_state").notNull(),
    toState: text("to_state").notNull(),
    byUserId: text("by_user_id")
      .notNull()
      .references(() => user.id),
    reason: text("reason"),
    createdAt: createdAt(),
  },
  (t) => [index("transitions_project_idx").on(t.projectId)]
);

export const MILESTONE_STATUSES = ["PLANNED", "IN_PROGRESS", "DONE"] as const;
export type MilestoneStatus = (typeof MILESTONE_STATUSES)[number];

export const milestones = sqliteTable(
  "milestones",
  {
    id: id(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id),
    title: text("title").notNull(),
    // "what will exist" when this milestone is done
    deliverable: text("deliverable").notNull(),
    startDate: integer("start_date", { mode: "timestamp_ms" }).notNull(),
    dueDate: integer("due_date", { mode: "timestamp_ms" }).notNull(),
    status: text("status", { enum: MILESTONE_STATUSES })
      .notNull()
      .default("PLANNED"),
    completedAt: integer("completed_at", { mode: "timestamp_ms" }),
  },
  (t) => [index("milestones_project_idx").on(t.projectId)]
);

export const CAUSE_TAGS = [
  "WAITING_DECISION",
  "WAITING_EQUIPMENT",
  "TECHNICAL",
  "WAITING_EXTERNAL",
  "KNOWLEDGE_GAP",
  "OTHER",
] as const;
export type CauseTag = (typeof CAUSE_TAGS)[number];

export const BLOCKER_STATUSES = ["OPEN", "ESCALATED", "RESOLVED"] as const;
export type BlockerStatus = (typeof BLOCKER_STATUSES)[number];

export const blockers = sqliteTable(
  "blockers",
  {
    id: id(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id),
    description: text("description").notNull(),
    causeTag: text("cause_tag", { enum: CAUSE_TAGS }).notNull(),
    ownerId: text("owner_id").references(() => user.id),
    deadline: integer("deadline", { mode: "timestamp_ms" }).notNull(),
    status: text("status", { enum: BLOCKER_STATUSES }).notNull().default("OPEN"),
    resolutionNote: text("resolution_note"),
    createdAt: createdAt(),
    resolvedAt: integer("resolved_at", { mode: "timestamp_ms" }),
  },
  (t) => [
    index("blockers_status_idx").on(t.status),
    index("blockers_project_idx").on(t.projectId),
  ]
);

export const updates = sqliteTable(
  "updates",
  {
    id: id(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id),
    whatMoved: text("what_moved").notNull(),
    whatsBlocked: text("whats_blocked").notNull().default(""),
    whatsNext: text("whats_next").notNull(),
    authorId: text("author_id")
      .notNull()
      .references(() => user.id),
    createdAt: createdAt(),
  },
  (t) => [index("updates_project_created_idx").on(t.projectId, t.createdAt)]
);

export const DECISION_STATUSES = ["PENDING", "DECIDED", "AUTO_PROCEEDED"] as const;
export type DecisionStatus = (typeof DECISION_STATUSES)[number];

export const decisions = sqliteTable(
  "decisions",
  {
    id: id(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id),
    question: text("question").notNull(),
    // freeform, one option per line
    options: text("options").notNull(),
    recommendation: text("recommendation").notNull(),
    requestedFromId: text("requested_from_id")
      .notNull()
      .references(() => user.id),
    status: text("status", { enum: DECISION_STATUSES })
      .notNull()
      .default("PENDING"),
    decidedById: text("decided_by_id").references(() => user.id),
    decisionNote: text("decision_note"),
    createdAt: createdAt(),
    decidedAt: integer("decided_at", { mode: "timestamp_ms" }),
  },
  (t) => [
    index("decisions_status_idx").on(t.status),
    index("decisions_project_idx").on(t.projectId),
  ]
);

export const projectsRelations = relations(projects, ({ one, many }) => ({
  owner: one(user, {
    fields: [projects.ownerId],
    references: [user.id],
  }),
  advisor: one(user, {
    fields: [projects.advisorId],
    references: [user.id],
  }),
  milestones: many(milestones),
  blockers: many(blockers),
  updates: many(updates),
  decisions: many(decisions),
  transitions: many(stateTransitions),
}));

export const stateTransitionsRelations = relations(stateTransitions, ({ one }) => ({
  project: one(projects, {
    fields: [stateTransitions.projectId],
    references: [projects.id],
  }),
  byUser: one(user, {
    fields: [stateTransitions.byUserId],
    references: [user.id],
  }),
}));

export const milestonesRelations = relations(milestones, ({ one }) => ({
  project: one(projects, {
    fields: [milestones.projectId],
    references: [projects.id],
  }),
}));

export const blockersRelations = relations(blockers, ({ one }) => ({
  project: one(projects, {
    fields: [blockers.projectId],
    references: [projects.id],
  }),
  owner: one(user, {
    fields: [blockers.ownerId],
    references: [user.id],
  }),
}));

export const updatesRelations = relations(updates, ({ one }) => ({
  project: one(projects, {
    fields: [updates.projectId],
    references: [projects.id],
  }),
  author: one(user, {
    fields: [updates.authorId],
    references: [user.id],
  }),
}));

export const decisionsRelations = relations(decisions, ({ one }) => ({
  project: one(projects, {
    fields: [decisions.projectId],
    references: [projects.id],
  }),
  requestedFrom: one(user, {
    fields: [decisions.requestedFromId],
    references: [user.id],
  }),
  decidedBy: one(user, {
    fields: [decisions.decidedById],
    references: [user.id],
  }),
}));

export type User = typeof user.$inferSelect;
export type Project = typeof projects.$inferSelect;
export type StateTransition = typeof stateTransitions.$inferSelect;
export type Milestone = typeof milestones.$inferSelect;
export type Blocker = typeof blockers.$inferSelect;
export type Update = typeof updates.$inferSelect;
export type Decision = typeof decisions.$inferSelect;
