import { sqliteTable, text, integer, index } from "drizzle-orm/sqlite-core";
import { relations } from "drizzle-orm";
import { user } from "./auth-schema";

// Auth tables (user, session, account, verification) are generated by
// better-auth: `npx @better-auth/cli generate`. Domain tables live here.
export * from "./auth-schema";

const id = () =>
  text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID());

const createdAt = () =>
  integer("created_at", { mode: "timestamp_ms" })
    .notNull()
    .$defaultFn(() => new Date());

// Project states are admin-defined (see lib/workflow.ts) — the column is
// plain TEXT holding a workflow state key. The stock keys live in
// DEFAULT_WORKFLOW (lib/settings-defaults.ts).

export const projects = sqliteTable(
  "projects",
  {
    id: id(),
    title: text("title").notNull(),
    description: text("description").notNull().default(""),
    ownerId: text("owner_id")
      .notNull()
      .references(() => user.id),
    advisorId: text("advisor_id")
      .notNull()
      .references(() => user.id),
    // who filed the proposal — counts as involvement for visibility
    createdById: text("created_by_id").references(() => user.id),
    state: text("state").notNull().default("PROPOSAL"),
    // required at app level whenever state === PAUSED
    pauseReason: text("pause_reason"),
    reviveDate: integer("revive_date", { mode: "timestamp_ms" }),
    // Heilmeier Catechism (the 7 built-in proposal questions)
    objective: text("objective").notNull().default(""),
    howItsDoneToday: text("how_its_done_today").notNull().default(""),
    whatsNew: text("whats_new").notNull().default(""),
    whoCares: text("who_cares").notNull().default(""),
    risks: text("risks").notNull().default(""),
    killCriteria: text("kill_criteria").notNull().default(""),
    successCriteria: text("success_criteria").notNull().default(""),
    // answers to admin-added custom proposal questions, keyed by question key
    extraAnswers: text("extra_answers", { mode: "json" })
      .$type<Record<string, string>>()
      .notNull()
      .default({}),
    createdAt: createdAt(),
  },
  (t) => [
    index("projects_state_idx").on(t.state),
    index("projects_owner_idx").on(t.ownerId),
  ]
);

export const stateTransitions = sqliteTable(
  "state_transitions",
  {
    id: id(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id),
    fromState: text("from_state").notNull(),
    toState: text("to_state").notNull(),
    byUserId: text("by_user_id")
      .notNull()
      .references(() => user.id),
    reason: text("reason"),
    createdAt: createdAt(),
  },
  (t) => [index("transitions_project_idx").on(t.projectId)]
);

export const MILESTONE_STATUSES = ["PLANNED", "IN_PROGRESS", "DONE", "CANCELLED"] as const;
export type MilestoneStatus = (typeof MILESTONE_STATUSES)[number];

export const milestones = sqliteTable(
  "milestones",
  {
    id: id(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id),
    title: text("title").notNull(),
    // "what will exist" when this milestone is done
    deliverable: text("deliverable").notNull(),
    startDate: integer("start_date", { mode: "timestamp_ms" }).notNull(),
    dueDate: integer("due_date", { mode: "timestamp_ms" }).notNull(),
    status: text("status", { enum: MILESTONE_STATUSES })
      .notNull()
      .default("PLANNED"),
    completedAt: integer("completed_at", { mode: "timestamp_ms" }),
  },
  (t) => [index("milestones_project_idx").on(t.projectId)]
);

// Blocker cause tags are admin-defined (settings.causeTags) — the column is
// plain TEXT holding a tag key. Stock tags: DEFAULT_CAUSE_TAGS.

// CANCELLED reuses resolutionNote/resolvedAt as closure note/time.
export const BLOCKER_STATUSES = ["OPEN", "ESCALATED", "RESOLVED", "CANCELLED"] as const;
export type BlockerStatus = (typeof BLOCKER_STATUSES)[number];

export const blockers = sqliteTable(
  "blockers",
  {
    id: id(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id),
    description: text("description").notNull(),
    causeTag: text("cause_tag").notNull(),
    ownerId: text("owner_id").references(() => user.id),
    // who raised it — feeds initiative-taking credit (null on legacy rows)
    raisedById: text("raised_by_id").references(() => user.id),
    deadline: integer("deadline", { mode: "timestamp_ms" }).notNull(),
    status: text("status", { enum: BLOCKER_STATUSES }).notNull().default("OPEN"),
    resolutionNote: text("resolution_note"),
    createdAt: createdAt(),
    resolvedAt: integer("resolved_at", { mode: "timestamp_ms" }),
  },
  (t) => [
    index("blockers_status_idx").on(t.status),
    index("blockers_project_idx").on(t.projectId),
  ]
);

export const updates = sqliteTable(
  "updates",
  {
    id: id(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id),
    whatMoved: text("what_moved").notNull(),
    whatsBlocked: text("whats_blocked").notNull().default(""),
    whatsNext: text("whats_next").notNull(),
    authorId: text("author_id")
      .notNull()
      .references(() => user.id),
    createdAt: createdAt(),
  },
  (t) => [index("updates_project_created_idx").on(t.projectId, t.createdAt)]
);

// CANCELLED reuses decisionNote/decidedAt as closure note/time.
export const DECISION_STATUSES = ["PENDING", "DECIDED", "AUTO_PROCEEDED", "CANCELLED"] as const;
export type DecisionStatus = (typeof DECISION_STATUSES)[number];

export const decisions = sqliteTable(
  "decisions",
  {
    id: id(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id),
    question: text("question").notNull(),
    // freeform, one option per line
    options: text("options").notNull(),
    recommendation: text("recommendation").notNull(),
    requestedFromId: text("requested_from_id")
      .notNull()
      .references(() => user.id),
    status: text("status", { enum: DECISION_STATUSES })
      .notNull()
      .default("PENDING"),
    decidedById: text("decided_by_id").references(() => user.id),
    decisionNote: text("decision_note"),
    createdAt: createdAt(),
    decidedAt: integer("decided_at", { mode: "timestamp_ms" }),
  },
  (t) => [
    index("decisions_status_idx").on(t.status),
    index("decisions_project_idx").on(t.projectId),
  ]
);

// Single-row settings store: { id: 1, data: <zod-validated JSON blob> }.
// Shape and defaults live in src/lib/settings.ts.
export const labSettings = sqliteTable("lab_settings", {
  id: integer("id").primaryKey(),
  data: text("data", { mode: "json" }).$type<unknown>().notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .notNull()
    .$defaultFn(() => new Date()),
});

// CANCELLED reuses deliveryNote/deliveredAt as closure note/time.
export const DATA_REQUEST_STATUSES = ["OPEN", "DELIVERED", "CANCELLED"] as const;
export type DataRequestStatus = (typeof DATA_REQUEST_STATUSES)[number];

export const dataRequests = sqliteTable(
  "data_requests",
  {
    id: id(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id),
    // what data is needed
    title: text("title").notNull(),
    description: text("description").notNull(),
    neededBy: integer("needed_by", { mode: "timestamp_ms" }).notNull(),
    requesterId: text("requester_id")
      .notNull()
      .references(() => user.id),
    // a data analyst; null → unowned, escalates via the fight engine
    assigneeId: text("assignee_id").references(() => user.id),
    status: text("status", { enum: DATA_REQUEST_STATUSES }).notNull().default("OPEN"),
    deliveryNote: text("delivery_note"),
    createdAt: createdAt(),
    deliveredAt: integer("delivered_at", { mode: "timestamp_ms" }),
  },
  (t) => [
    index("data_requests_status_idx").on(t.status),
    index("data_requests_project_idx").on(t.projectId),
  ]
);

// Server types and optimization practices are admin-defined
// (settings.serverTypes / settings.practices) — plain TEXT key columns.
// Stock lists: DEFAULT_SERVER_TYPES / DEFAULT_PRACTICES.

export const COMPUTE_REQUEST_STATUSES = [
  "PENDING",
  "APPROVED",
  "DENIED",
  "COMPLETED",
  "WITHDRAWN",
] as const;
export type ComputeRequestStatus = (typeof COMPUTE_REQUEST_STATUSES)[number];

export const computeRequests = sqliteTable(
  "compute_requests",
  {
    id: id(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id),
    requesterId: text("requester_id")
      .notNull()
      .references(() => user.id),
    serverType: text("server_type").notNull(),
    hoursNeeded: integer("hours_needed").notNull(),
    // justification + utilization plan (sweeps/ablations, schedule, metrics)
    justification: text("justification").notNull(),
    datasetSize: text("dataset_size").notNull(),
    preprocessingNote: text("preprocessing_note").notNull(),
    dryRunEvidence: text("dry_run_evidence").notNull(),
    expectedResults: text("expected_results").notNull(),
    optimizations: text("optimizations", { mode: "json" })
      .$type<string[]>()
      .notNull(),
    status: text("status", { enum: COMPUTE_REQUEST_STATUSES })
      .notNull()
      .default("PENDING"),
    decidedById: text("decided_by_id").references(() => user.id),
    decidedAt: integer("decided_at", { mode: "timestamp_ms" }),
    // set on APPROVED: how to get on the machine (NVIDIA Brev link etc.)
    accessInstructions: text("access_instructions"),
    // set on APPROVED: when the allocated hours expire
    windowEnd: integer("window_end", { mode: "timestamp_ms" }),
    denialReason: text("denial_reason"),
    // final outcomes vs expected — owed after the window ends
    resultsSummary: text("results_summary"),
    completedAt: integer("completed_at", { mode: "timestamp_ms" }),
    createdAt: createdAt(),
  },
  (t) => [
    index("compute_requests_status_idx").on(t.status),
    index("compute_requests_project_idx").on(t.projectId),
  ]
);

// CANCELLED reuses completionNote/completedAt as closure note/time.
export const TASK_STATUSES = ["OPEN", "DONE", "CANCELLED"] as const;
export type TaskStatus = (typeof TASK_STATUSES)[number];

// General-purpose lab tasks, handled by SECRETARY-role users. Standalone,
// with an optional project link; deadlines feed the fight engine.
export const tasks = sqliteTable(
  "tasks",
  {
    id: id(),
    title: text("title").notNull(),
    description: text("description").notNull().default(""),
    deadline: integer("deadline", { mode: "timestamp_ms" }).notNull(),
    requesterId: text("requester_id")
      .notNull()
      .references(() => user.id),
    // a secretary; null → unowned, escalates via the fight engine
    assigneeId: text("assignee_id").references(() => user.id),
    projectId: text("project_id").references(() => projects.id),
    status: text("status", { enum: TASK_STATUSES }).notNull().default("OPEN"),
    completionNote: text("completion_note"),
    createdAt: createdAt(),
    completedAt: integer("completed_at", { mode: "timestamp_ms" }),
  },
  (t) => [
    index("tasks_status_idx").on(t.status),
    index("tasks_assignee_idx").on(t.assigneeId),
  ]
);

// WON/LOST/CANCELLED reuse closureNote/closedAt as closure note/time.
export const INITIATIVE_STATUSES = ["OPEN", "WON", "LOST", "CANCELLED"] as const;
export type InitiativeStatus = (typeof INITIATIVE_STATUSES)[number];

// "Big fights" from the weekly meeting — equipment, budgets, university
// management. Lab-level (no project link), leadership-only surface.
export const initiatives = sqliteTable(
  "initiatives",
  {
    id: id(),
    title: text("title").notNull(),
    description: text("description").notNull().default(""),
    deadline: integer("deadline", { mode: "timestamp_ms" }).notNull(),
    requesterId: text("requester_id")
      .notNull()
      .references(() => user.id),
    // a manager or the compute coordinator; null → unowned, escalates
    assigneeId: text("assignee_id").references(() => user.id),
    status: text("status", { enum: INITIATIVE_STATUSES }).notNull().default("OPEN"),
    closureNote: text("closure_note"),
    createdAt: createdAt(),
    closedAt: integer("closed_at", { mode: "timestamp_ms" }),
  },
  (t) => [
    index("initiatives_status_idx").on(t.status),
    index("initiatives_assignee_idx").on(t.assigneeId),
  ]
);

export const initiativesRelations = relations(initiatives, ({ one }) => ({
  requester: one(user, {
    fields: [initiatives.requesterId],
    references: [user.id],
  }),
  assignee: one(user, {
    fields: [initiatives.assigneeId],
    references: [user.id],
  }),
}));

export const FEEDBACK_KINDS = ["BUG", "IDEA"] as const;
export type FeedbackKind = (typeof FEEDBACK_KINDS)[number];
export const FEEDBACK_STATUSES = ["NEW", "PLANNED", "DONE", "DECLINED"] as const;
export type FeedbackStatus = (typeof FEEDBACK_STATUSES)[number];

// Bug reports and feature ideas from anyone in the lab; managers triage.
// Never deleted — declined items keep their reasons on the record.
export const feedback = sqliteTable(
  "feedback",
  {
    id: id(),
    kind: text("kind", { enum: FEEDBACK_KINDS }).notNull(),
    title: text("title").notNull(),
    body: text("body").notNull(),
    submitterId: text("submitter_id")
      .notNull()
      .references(() => user.id),
    status: text("status", { enum: FEEDBACK_STATUSES }).notNull().default("NEW"),
    adminResponse: text("admin_response"),
    respondedById: text("responded_by_id").references(() => user.id),
    createdAt: createdAt(),
    respondedAt: integer("responded_at", { mode: "timestamp_ms" }),
  },
  (t) => [index("feedback_status_idx").on(t.status)]
);

export const feedbackRelations = relations(feedback, ({ one }) => ({
  submitter: one(user, {
    fields: [feedback.submitterId],
    references: [user.id],
  }),
  respondedBy: one(user, {
    fields: [feedback.respondedById],
    references: [user.id],
  }),
}));

export const PROJECT_PEOPLE_ROLES = ["PI", "FIRST_AUTHOR", "CONTRIBUTOR"] as const;
export type ProjectPersonRole = (typeof PROJECT_PEOPLE_ROLES)[number];

// The project's human lineup — lab members AND people who never touch the
// app (students, external PIs, assistants). Exactly one PI and one
// FIRST_AUTHOR per project (enforced in actions with demote-on-swap);
// activation is blocked until both exist. Either userId (member) or
// externalName is set, never both. These rows are current-lineup metadata
// like projects.ownerId, not event history — removal is a plain delete
// (the one deliberate exception to the no-hard-deletes rule).
export const projectPeople = sqliteTable(
  "project_people",
  {
    id: id(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id),
    userId: text("user_id").references(() => user.id),
    externalName: text("external_name"),
    affiliation: text("affiliation"),
    role: text("role", { enum: PROJECT_PEOPLE_ROLES }).notNull().default("CONTRIBUTOR"),
    // free text shown next to contributors: "MSc student", "assistant"
    title: text("title").notNull().default(""),
    // watcher email for people outside the app; members use their account
    // email. notify=true opts the row into big-event project emails.
    email: text("email"),
    notify: integer("notify", { mode: "boolean" }).notNull().default(false),
    createdAt: createdAt(),
  },
  (t) => [index("project_people_project_idx").on(t.projectId)]
);

export const projectPeopleRelations = relations(projectPeople, ({ one }) => ({
  project: one(projects, {
    fields: [projectPeople.projectId],
    references: [projects.id],
  }),
  user: one(user, {
    fields: [projectPeople.userId],
    references: [user.id],
  }),
}));

export const PAPER_STATUSES = [
  "DRAFTING",
  "SUBMITTED",
  "ACCEPTED",
  "REJECTED",
  "WITHDRAWN",
] as const;
export type PaperStatus = (typeof PAPER_STATUSES)[number];

// Every project must lead to a Q1 paper — this is where that fight lives.
// One row = one logical manuscript; a rejection resubmitted to a new venue
// stays the same row (submittedAt refreshes, closure clears). REJECTED and
// WITHDRAWN reuse closureNote/closedAt as closure note/time.
export const papers = sqliteTable(
  "papers",
  {
    id: id(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id),
    title: text("title").notNull(),
    venue: text("venue").notNull().default(""),
    quartileNote: text("quartile_note").notNull().default(""),
    status: text("status", { enum: PAPER_STATUSES }).notNull().default("DRAFTING"),
    submittedAt: integer("submitted_at", { mode: "timestamp_ms" }),
    acceptedAt: integer("accepted_at", { mode: "timestamp_ms" }),
    closedAt: integer("closed_at", { mode: "timestamp_ms" }),
    closureNote: text("closure_note"),
    link: text("link").notNull().default(""),
    createdById: text("created_by_id").references(() => user.id),
    createdAt: createdAt(),
  },
  (t) => [index("papers_project_idx").on(t.projectId)]
);

export const papersRelations = relations(papers, ({ one }) => ({
  project: one(projects, {
    fields: [papers.projectId],
    references: [projects.id],
  }),
  createdBy: one(user, {
    fields: [papers.createdById],
    references: [user.id],
  }),
}));

export const projectsRelations = relations(projects, ({ one, many }) => ({
  owner: one(user, {
    fields: [projects.ownerId],
    references: [user.id],
  }),
  advisor: one(user, {
    fields: [projects.advisorId],
    references: [user.id],
  }),
  milestones: many(milestones),
  blockers: many(blockers),
  updates: many(updates),
  decisions: many(decisions),
  transitions: many(stateTransitions),
  dataRequests: many(dataRequests),
  computeRequests: many(computeRequests),
  tasks: many(tasks),
  people: many(projectPeople),
  papers: many(papers),
}));

export const tasksRelations = relations(tasks, ({ one }) => ({
  project: one(projects, {
    fields: [tasks.projectId],
    references: [projects.id],
  }),
  requester: one(user, {
    fields: [tasks.requesterId],
    references: [user.id],
  }),
  assignee: one(user, {
    fields: [tasks.assigneeId],
    references: [user.id],
  }),
}));

export const computeRequestsRelations = relations(computeRequests, ({ one }) => ({
  project: one(projects, {
    fields: [computeRequests.projectId],
    references: [projects.id],
  }),
  requester: one(user, {
    fields: [computeRequests.requesterId],
    references: [user.id],
  }),
  decidedBy: one(user, {
    fields: [computeRequests.decidedById],
    references: [user.id],
  }),
}));

export const dataRequestsRelations = relations(dataRequests, ({ one }) => ({
  project: one(projects, {
    fields: [dataRequests.projectId],
    references: [projects.id],
  }),
  requester: one(user, {
    fields: [dataRequests.requesterId],
    references: [user.id],
  }),
  assignee: one(user, {
    fields: [dataRequests.assigneeId],
    references: [user.id],
  }),
}));

export const stateTransitionsRelations = relations(stateTransitions, ({ one }) => ({
  project: one(projects, {
    fields: [stateTransitions.projectId],
    references: [projects.id],
  }),
  byUser: one(user, {
    fields: [stateTransitions.byUserId],
    references: [user.id],
  }),
}));

export const milestonesRelations = relations(milestones, ({ one }) => ({
  project: one(projects, {
    fields: [milestones.projectId],
    references: [projects.id],
  }),
}));

export const blockersRelations = relations(blockers, ({ one }) => ({
  project: one(projects, {
    fields: [blockers.projectId],
    references: [projects.id],
  }),
  owner: one(user, {
    fields: [blockers.ownerId],
    references: [user.id],
  }),
}));

export const updatesRelations = relations(updates, ({ one }) => ({
  project: one(projects, {
    fields: [updates.projectId],
    references: [projects.id],
  }),
  author: one(user, {
    fields: [updates.authorId],
    references: [user.id],
  }),
}));

export const decisionsRelations = relations(decisions, ({ one }) => ({
  project: one(projects, {
    fields: [decisions.projectId],
    references: [projects.id],
  }),
  requestedFrom: one(user, {
    fields: [decisions.requestedFromId],
    references: [user.id],
  }),
  decidedBy: one(user, {
    fields: [decisions.decidedById],
    references: [user.id],
  }),
}));

export type User = typeof user.$inferSelect;
export type DataRequest = typeof dataRequests.$inferSelect;
export type ComputeRequest = typeof computeRequests.$inferSelect;
export type Project = typeof projects.$inferSelect;
export type StateTransition = typeof stateTransitions.$inferSelect;
export type Milestone = typeof milestones.$inferSelect;
export type Blocker = typeof blockers.$inferSelect;
export type Update = typeof updates.$inferSelect;
export type Decision = typeof decisions.$inferSelect;
export type Task = typeof tasks.$inferSelect;
export type Initiative = typeof initiatives.$inferSelect;
export type Feedback = typeof feedback.$inferSelect;
export type ProjectPerson = typeof projectPeople.$inferSelect;
export type Paper = typeof papers.$inferSelect;
